### ISSUE TITLE
Headers for C?

### ISSUE THREAD

**Issue by jsinglet** [p12tic/cppreference-doc#119]
In this repo the headers for C++ are present. Is a similar effort available for the C headers (eg, string.h, etc) available? I notice those headers are described on cppreference so I was curious where I might find those. Thanks!

**Comment by p12tic** [comment]
I personally use C++ that's why I focused in C++ headers. I think this could be a good place for C headers too. I'm not aware of anyone solving a similar problem.

**Comment by cubbimew** [comment]
cpp/headers is populated from the header synopses found in the C++ standard, for example https://en.cppreference.com/w/cpp/header/array is populated from https://eel.is/c++draft/array.syn  (personally I think it's unnecessary but a lot of people seem to look for meaning to headers)

The C standard doesn';t offer such synopses - each header is just followed by the description of the library components associated with it, which cppreference already does, more or less, at https://en.cppreference.com/w/c/header
