### ISSUE TITLE
Under attack by Rust programmers!

### ISSUE THREAD

**Issue by Herotako** [p12tic/cppreference-doc#133]
As of August 1, 2023, there have been attacks on this site with posts saying Rust is the best and links changed to Rust's Wikipedia.
Once this has been corrected, it appears to have been fixed, but the number of attacks has increased since the beginning of this year, so I decided to report it and list it on the issue.

**Comment by PeterFeicht** [comment]
This repo is for the offline archive of the site. Please take a look at the discussion pages on the site for content-related discussion.
