### ISSUE TITLE
Anki 2.0 Deck creation

### ISSUE THREAD

**Issue by timoc** [p12tic/cppreference-doc#22]
This is a follow-up to the post on the website: 

Where would i start looking to implement a simple CSV file along these lines?

> Anki renders the cards as HTML in the interface, so i have essentially spammed the 
> default card stylesheet with the cppreference stylesheet to keep the page formatting. 
> It seems that every section/linkable keyword correlates to an 'answer' or concept worth 
> remembering. The hardest part is of course generating questions. My idea (at least for
> a first approximation) was to generate the card/question list from the section/keyword
> list + context in tree. Imagine each section as a flashcard. for example: 
>     Q: What is: Operator Overloading (C++ Language, Expressions)

**Comment by p12tic** [comment]
Closing as obsolete.
