### ISSUE TITLE
Could you add new format(zim) of offline archive?

### ISSUE THREAD

**Issue by zjzengdongyang** [p12tic/cppreference-doc#25]
Could you add new format(zim) of offline archive?
You can use zimwriterfs to pack those html files.
I think it is a good idea.
Because we can read this doc in many devices(for example android) only 1 file(use kiwix or kiwix-serve).
And we can  Full text search.
Also you can let kiwix help you build this doc.I think they will be happy to help.
zimwriterfs is a console tool to create ZIM (http://www.openzim.org)
files from a localy stored directory containing a "self-sufficient"
HTML content (with pictures, javascript, stylesheets). The result will
contain all the files of the local directory compressed and merged in
the ZIM file. Nothing more, nothing less. The generated file can be
open with a ZIM reader, Kiwix (http://www.kiwix.org) for example, but
you have other one (http://openzim.org/wiki/ZIM_Readers).
https://sourceforge.net/p/kiwix/other/ci/master/tree/zimwriterfs/

**Comment by p12tic** [comment]
Closing as obsolete.
