### ISSUE TITLE
Possible output errors in utility/move

### ISSUE THREAD

**Issue by zuyu** [p12tic/cppreference-doc#35]
[utility/move](http://en.cppreference.com/w/cpp/utility/move)

The following results are generated from Apple Clang 7 on Mac OS X 10.11. And I believe the output of the last line would never be 'Hello', shown in the above page.

```
After copy, str is "Hello"
After move, str is ""
The contents of the vector are "Hello", "Hello"
Before move from str2, str2 = 'Good-bye'
After move from str2, str2 = **''**
```

**Comment by cpplearner** [comment]
http://en.cppreference.com/w/talk:cpp/utility/move might be a better place for you to report this issue.

**Comment by p12tic** [comment]
Closing as already resolved.
