### ISSUE TITLE
Doxygen tagfile should link headers

### ISSUE THREAD

**Issue by mikepurvis** [p12tic/cppreference-doc#41]
The following output from a doxygen source listing:

```
#include <vector>
```

Does not link to http://en.cppreference.com/w/cpp/header/vector

**Comment by mikepurvis** [comment]
Based on how the rest of the library works, I'd say [this index file](https://github.com/p12tic/cppreference-doc/blob/0e8f2341c835036616a60070a53b8dc7d11d8af2/index-chapters-cpp.xml#L18) would need to be expanded to include `<sub ... />` entries corresponding to relevant links from the parent page: http://en.cppreference.com/w/cpp/header

And then in `index2doxygen-tag.py`, basically just add a sibling function to `print_map` like `print_headers` to handle outputting a Doxygen-friendly entry for each one. Which looks approximately like this:

```
  <compound kind="file">
    <name>vector</name>
    <filename>cpp/header/vector</filename>
    <namespace>std</namespace>
  </compound>
```

@p12tic Would you entertain a PR for the proposed changes?

**Comment by p12tic** [comment]
Hi, thanks a lot for the investigation. The feature request makes sense, I would be very happy if it's implemented.

**Comment by PeterFeicht** [comment]
Should this be closed?

**Comment by p12tic** [comment]
Yes, thanks for noticing.
