### ISSUE TITLE
The offline archive is unreadable

### ISSUE THREAD

**Issue by Wolk** [p12tic/cppreference-doc#42]
Hello, i wanted to get the offline version of the archive, but it's unformated.
I cannot read anything out of it, it doesn't look anything like the website. I believe it didn't import it correctly.

link: http://en.cppreference.com/w/File:cppreference-doc-20161029.zip

**Comment by p12tic** [comment]
Hi, it works fine on my end. Which specific page did you have problems with?

**Comment by Wolk** [comment]
Hello, reading index.html from cppreference-doc-20161029\reference\en.cppreference.com
gives me the following result:
http://imgur.com/a/JJMsj

**Comment by p12tic** [comment]
Okay, so it could be that Windows support has been broken :-( Does the 29 November 2015 version work on your setup?

**Comment by p12tic** [comment]
Also, does the "Html book" version of the archive work for you? The "raw archive" version is raw copy made on Unix machine with no further postprocessing to fix issues that happen on other operating systems.

**Comment by Wolk** [comment]
Tested the 29nov archive, it has the same issue. The Html book version however, works.

**Comment by p12tic** [comment]
Do you need some specific stuff that is in the 'raw archive' but not in 'html book'? The html book is the preferred way to access the offline archive. I guess we need to clarify that in the http://en.cppreference.com/w/Cppreference:Archives page.

**Comment by Wolk** [comment]
I was trying to get the full archive down, as opposed to the stripped version, i thought that was the preferred way. The html book will suffice for offline work :)

**Comment by p12tic** [comment]
I will close the issue then. Thanks for bringing this to light, there probably were many users who were confused by this.
