### ISSUE TITLE
Use https

### ISSUE THREAD

**Issue by SylvainCorlay** [p12tic/cppreference-doc#49]
I am embedding pages from cppreference in an iframe from a web app (the jupyter notebook), which fetches the resources from cppreference based on some tag file.

The problem is that when the connection to jupyter is https, the CORS setting disallow loading content from an insecure source. Would it be possible for cppreference to be served over https?

**Comment by p12tic** [comment]
Could you ask this question on http://en.cppreference.com/w/Talk:Main_Page? The hosting of the website is handled by Nate Kohl, I don't think he monitors this repository.

**Comment by SylvainCorlay** [comment]
Thanks! Closing this issue.

**Comment by SylvainCorlay** [comment]
It does not seem that I have permission to contribute to this page on the wiki.

cc @natekohl

**Comment by p12tic** [comment]
I've unprotected the page temporarily, you can edit now. Sorry for not checking earlier.

**Comment by SylvainCorlay** [comment]
Thanks. I could edit the comments page! 👍

**Comment by sigurdurb** [comment]
@SylvainCorlay Seems like nothing has been done about serving cppreference over https huh? Did you find any other fix ? I am running jupyterhub over https for my uni.

**Comment by SylvainCorlay** [comment]
Hey @sigurdurb sorry for the late reply.

There has been some discussion with @natekohl and @yuvipanda about how to fix this and configure the old version of mediawiki used by cppreference, but no solution to the issue yet unfortunately.

Regarding your use at your Uni, are you using xeus-cling for C++?

**Comment by p12tic** [comment]
Would upgrading MediaWiki to newer version make https support easier? Upgrading will need code changes to the skins though, I have most of that done some time ago, but it's not tested properly yet.

**Comment by sigurdurb** [comment]
@SylvainCorlay Yes, I have it with xeus-cling. Right now I am just testing it but maybe next fall we will start using it with Jupyterhub.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay Yes, I have it with xeus-cling. Right now I am just testing it but maybe next fall we will start using it with Jupyterhub.

Awesome! If you have any question on xeus-cling, don't hesitate to hop on our permanent chat. https://gitter.im/QuantStack/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by natekohl** [comment]
@Povilas -- I suspect upgrading MediaWiki would help make https easier, but
I'm not entirely sure. I think you're right about needing code changes to
the skins, though -- I tried upgrading a few weeks ago and everything kinda
broke. :P

Do you happen to know what kind of code changes the skins would need?

**Comment by p12tic** [comment]
The changes are in the [upgrade-1.27 branch](https://github.com/p12tic/cppreference-doc/tree/upgrade-1.27). They have been done long ago, I don't remember the state of that code.

I'm currently mentoring a programmer that could look into this in several weeks.

**Comment by natekohl** [comment]
Oh! That would be spiffy. :)

**Comment by povilas** [comment]
huh? :)

**Comment by sigurdurb** [comment]
Hmm, why is CSS working over HTTPS for [https://en.cppreference.com/w/cpp/container/map](https://en.cppreference.com/w/cpp/container/map)
but not the other pages, like [https://en.cppreference.com/w/cpp/container/vector](https://en.cppreference.com/w/cpp/container/vector)

**Comment by p12tic** [comment]
I think that if Nate has turned on https temporarily, then some pages might have been cached within MediaWiki with https links to stylesheets, thus they work.

@natekohl: Could it be that the reason you saw https not working was that you saw cached pages? I think MediaWiki does not purge HTTP cache after configuration changes. A quick way to verify would be to add `?action=purge` when https is on.

**Comment by natekohl** [comment]
holy crap, purging indeed fixes
https://en.cppreference.com/w/cpp/container/vector. i'm gonna kick myself
if that's all we needed to do this whole time

**Comment by SylvainCorlay** [comment]
woot!

**Comment by SylvainCorlay** [comment]
This seems to work, but we still need to do `?action=purge` on each new page (I just did it on the front page).
Can it be done globally?

**Comment by natekohl** [comment]
I just purged the global cache; in theory, all pages should be re-created
as they are visited now.

**Comment by natekohl** [comment]
hm, touching the file that defines $wgCacheEpoch seems to have only
partially worked. I wonder if there is a race between HTTP and HTTPS
traffic to get into the cache or something...

**Comment by p12tic** [comment]
@natekohl I think you can just delete the directories within the cache directory - that's where all the html files reside. Be sure not to delete .htaccess accidentally :-)

**Comment by natekohl** [comment]
ah, $wgCacheEpoch probably only works on old MW installations. I'll try to
figure out the new way to invalidate all cache entries.

**Comment by natekohl** [comment]
I tried deleting the cache/ and was...somewhat...successful. Parts of it
weren't deletable, presumably because they were being concurrently written
to by MediaWiki.

**Comment by natekohl** [comment]
A more thorough delete of the cache didn't seem to help. Pages loaded via
HTTPS still try to load HTTP stylesheets, until ?action=purge is appended,
after which they correctly load HTTPS stylesheets.

**Comment by p12tic** [comment]
@natekohl It seems there are other caches where various bits of information are cached. Maybe running [`purgeList.php --all --purge`](https://www.mediawiki.org/wiki/Manual:PurgeList.php) maintenance script would help?

**Comment by p12tic** [comment]
@SylvainCorlay: The http://cdn.jsdelivr.net/ace/1.2.4/noconflict/ace.js script issue is caused by https://github.com/p12tic/cppreference-doc/blob/master/gadgets/coliru_compiler.js#L548. I've fixed this few seconds ago on the wiki. Unfortunately it seems that http://coliru.stacked-crooked.com/ does not yet support https and we will need some kind of workaround for the "Run this code" button to work.

**Comment by timsong-cpp** [comment]
It looks like a competing cache issue. Have we tried setting [`$wgServer`](https://www.mediawiki.org/wiki/Manual:$wgServer) to a protocol-relative URL?

**Comment by natekohl** [comment]
Maybe switching over $wgServer to https has helped with the competing cache
problem -- let's see if it sticks.

In the meantime, it looks like the syntax-highlighted links generated by
GeSHi are hardcoded to http, so pages like
https://en.cppreference.com/w/cpp/utility/tuple/make_tuple will have a mix
of https and http links.

**Comment by timsong-cpp** [comment]
I meant a protocol-relative URL like `//en.cppreference.com` etc. (which will follow whatever protocol you are currently using), not just making it https.

The GeSHi thing is probably hardcoded somewhere and should be switched over.
