### ISSUE TITLE
[REQUEST] Update offline archive

### ISSUE THREAD

**Issue by NSbuilder** [p12tic/cppreference-doc#50]
The [offline archive](http://en.cppreference.com/w/Cppreference:Archives) is old and outdated.

Can you please update the offline archive ( HTML Book )? I tried to contact the website with their mail but I didn't get any respond...

**Comment by PeterFeicht** [comment]
In the meantime, you can get a more recent version at [my fork](https://github.com/PeterFeicht/cppreference-doc) (under releases). It's not 100% identical, see the readme for details.

**Comment by marehr** [comment]
@PeterFeicht could you update the wikipages? As I see it, everyone should be able to edit the wiki pages. And you seem to be familiar how to generate the archives.

**Comment by PeterFeicht** [comment]
Done. I also removed the unofficial archive someone added a month ago, since that was just a badly executed rip of the site (including special pages and all).

**Comment by marehr** [comment]
@PeterFeicht Did someone remove it again?

**Comment by marehr** [comment]
@PeterFeicht Thank you! (found it)
