### ISSUE TITLE
Feature request: select language version

### ISSUE THREAD

**Issue by Eelis** [p12tic/cppreference-doc#75]
It's really nice that pages like https://en.cppreference.com/w/cpp/language/constexpr include information about many versions of the language! That said, if one happens to just be interested in a specific version of the language, then the inapplicable information can be a bit noisy and distracting. For example, quite often all I want to know is "how does feature X work in C++17?", not "what was the detailed evolution of feature X over the complete history of C++?".

So maybe a useful feature could be to have a button somewhere near the top of the page, that lets the user select a language version. The effect of selecting a language version would be that text inapplicable to that standard version would be omitted. For example, if you select C++17, then obsolete rules that only applied "(until C++14)" or "(until C++17)" would not be shown.

What do you think? :)

**Comment by timsong-cpp** [comment]
It exists (in an alpha/beta form). You need to get an account, then enable `<gadget-StandardRevisions>` in your preferences.

**Comment by Eelis** [comment]
Ah, awesome! Thanks, then I'll close this ticket.

**Comment by PeterFeicht** [comment]
How does that apply to the offline version then, does it even include gadgets?
